Create two vectors (A and B), where A is (1,2,3) and B is (4,5,6). With these vectors, use the cbind() or rbind() function to create a 2 x 3 matrix from the vectors. Based on the output, determine the appropriate function to use.

In [6]:
A <- c(1,2,3)
B <- c(4,5,6)

rbind(A,B)

[,1] [,2] [,3]
A 1    2    3   
B 4    5    6

Create a 3 x 3 matrix consisting of the numbers 1-9. Create this matrix using the shortcut 1:9 and by specifying the nrow argument in the matrix() function call. Assign this matrix to the variable *mat

In [7]:
mat <- matrix(1:9, nrow = 3)
mat

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

Confirm that mat is a matrix

In [8]:
is.matrix(mat)

[1] TRUE

Create a 5 x 5 matrix consisting of the numbers 1-25 and assign it to the variable mat2. The top row should be the numbers 1-5

In [10]:
mat2 <- matrix(1:25, byrow=TRUE, nrow = 5)
mat2

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

Use index notation to grab a subsection of mat2 that replicates the output

In [13]:
mat2[2:3,2:3]

[,1] [,2]
[1,]  7    8  
[2,] 12   13

Use index notation to grab a subsection of mat2 that replicates the output

In [14]:
mat2[4:5,4:5]

[,1] [,2]
[1,] 19   20  
[2,] 24   25

What is the sum of all of the elements of mat2?

In [15]:
sum(mat2)

[1] 325

Find out how to use the Built-in R Function runif() to create a 4 x 5 matrix consisting of 20 random numbers

In [16]:
help(runif)

In [22]:
mat3 <- matrix(runif(20, 1, 100), nrow = 4)
mat3

[,1]     [,2]      [,3]      [,4]     [,5]    
[1,] 73.84115 29.967546  1.521954 12.65610 99.96266
[2,] 70.66285  4.546596 68.329041 49.51800 27.76018
[3,] 33.80784 96.671873 41.467542 13.51297 37.63931
[4,] 80.49115  3.945654 21.291354 77.29695 94.05478